version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: zl0y-postgres
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: tanryberdi
      POSTGRES_PASSWORD: tanryberdi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zl0y-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d billing"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Database
  mongodb:
    image: mongo:7.0.9
    container_name: zl0y-mongodb
    environment:
      MONGO_INITDB_DATABASE: billing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - zl0y-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Billing Service
  billing:
    build: .
    container_name: zl0y-billing
    environment:
      PORT: 8080
      POSTGRES_DSN: postgres://tanryberdi:tanryberdi@postgres:5432/billing?sslmode=disable
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DATABASE: billing
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - zl0y-network
    restart: unless-stopped

networks:
  zl0y-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data: